- hosts: all
  become: true
  tasks:

   - name: update repository index
     apt: 
      update_cache: yes
     when: ansible_distribution == "Ubuntu" 


   - name: Install Apache
     apt: name=apache2 state=present
     when: ansible_distribution == "Ubuntu" 
