- hosts: all
  become: true
  tasks:
    - name: install updates
      ansible.builtin.apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes
        purge: true
        clean: yes
      when: ansible_distribution == "Ubuntu"

- hosts: Ubuntu
  become: true
  tasks:
    - name: install apache
      ansible.builtin.apt:
        pkg:
          - apache2
          - libapache2-mod-php
        state: latest
      
- hosts: Unifi
  become: true
  tasks:
    - name: Update Unifi
      ansible.builtin.apt:
        name: unifi         
        state: latest
        autoremove: yes
      when: ansible_distribution == "Ubuntu"