- hosts: all
  become: true
  tasks:
  
   - name: install updates
     package: 
      update_only: yes
      update_cache: yes
     when: ansible_distribution == "Ubuntu" 


- hosts: Ubuntu
  become: true
  tasks:
  
   - name: install updates
     apt: 
      name:
        - apache2
        - libapache2-mod-php
      state: latest
     when: ansible_distribution == "Ubuntu"